# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activeagents-telemetry` gem.
# Please instead update this file by running `bin/tapioca gem activeagents-telemetry`.


# Shared core for reporting LLM traces to ActiveAgents.
#
# This gem carries no integration of its own — it owns the wire format, the
# configuration, and delivery. Install an adapter for whatever your app calls
# the model through:
#
#   gem "activeagents-telemetry-ruby_llm"   # apps built on RubyLLM
#
# Configure the destination once and every adapter inherits it:
#
#   ActiveAgents::Telemetry.configure do |config|
#     config.api_key      = ENV["ACTIVEAGENTS_API_KEY"]
#     config.service_name = "my-app"
#   end
#
# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/version.rb:3
module ActiveAgents; end

# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/version.rb:4
module ActiveAgents::Telemetry
  class << self
    # Replaces configuration wholesale; mostly useful in tests.
    #
    # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry.rb:29
    def configuration; end

    # Replaces configuration wholesale; mostly useful in tests.
    #
    # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry.rb:39
    def configuration=(_arg0); end

    # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry.rb:33
    def configure; end

    # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry.rb:52
    def enabled?; end

    # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry.rb:46
    def reporter; end

    # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry.rb:50
    def reporter=(_arg0); end

    # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry.rb:41
    def reset!; end
  end
end

# A Reporter that buffers traces and delivers them in batches — fewer
# HTTP requests under sustained traffic, at the cost of traces arriving
# up to flush_interval seconds late.
#
# A full buffer (configuration.batch_size) flushes immediately; a
# background thread flushes whatever accumulated every
# configuration.flush_interval seconds. Call #shutdown before process
# exit or the tail of the buffer is lost.
#
# Sampling happens on enqueue, so a dropped trace never occupies buffer
# space; enabled?/configured? are also checked on enqueue AND inherited
# from Reporter#report at delivery time.
#
# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/batching_reporter.rb:17
class ActiveAgents::Telemetry::BatchingReporter < ::ActiveAgents::Telemetry::Reporter
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/batching_reporter.rb:18
  def initialize(configuration, **options); end

  # Delivers everything buffered, blocking until done.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/batching_reporter.rb:46
  def flush; end

  # Enqueues a trace, flushing if the batch is full.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/batching_reporter.rb:28
  def report(traces); end

  # Flushes, waits out in-flight sends, and stops the background thread —
  # traces reported just before process exit are delivered, not dropped.
  # Idempotent.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/batching_reporter.rb:55
  def shutdown; end

  private

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/batching_reporter.rb:65
  def deliver_batch(batch, blocking: T.unsafe(nil)); end

  # Lazily started so a reporter constructed at boot in a process that
  # never traces (a console, a one-off rake task) spawns no thread.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/batching_reporter.rb:81
  def start_flusher; end
end

# Where traces go and how they get there.
#
# Every adapter takes one of these, so an app configures the destination
# once and each adapter inherits it:
#
#   ActiveAgents::Telemetry.configure do |config|
#     config.api_key      = ENV["ACTIVEAGENTS_API_KEY"]
#     config.service_name = "my-app"
#     config.environment  = Rails.env
#   end
#
# A self-hosted ActiveAgent dashboard is the same thing with a different
# endpoint — point it at "https://your-app.example.com/active_agent/api/traces".
#
# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:18
class ActiveAgents::Telemetry::Configuration
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:35
  def initialize; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def api_key; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def api_key=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def async; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def async=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:79
  def async?; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def batch_size; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def batch_size=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def capture_bodies; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def capture_bodies=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:75
  def capture_bodies?; end

  # Traces are only sent when there is somewhere to send them: an endpoint
  # plus something to authenticate with, or a local store that bypasses
  # HTTP entirely.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:58
  def configured?; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def enabled; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def enabled=(_arg0); end

  # An explicit kill-switch over and above configured?. Defaults to true —
  # for adapters, the presence of an api_key remains the effective switch;
  # frameworks that want opt-in default this to false.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:65
  def enabled?; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def endpoint; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def endpoint=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def environment; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def environment=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def error_message_limit; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def error_message_limit=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def flush_interval; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def flush_interval=(_arg0); end

  # Loads settings from a hash — how config/*.yml files reach here.
  # Unknown keys are ignored, so a newer config file works on an older
  # gem; numeric settings are coerced because ERB-interpolated YAML
  # values arrive as strings.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:99
  def load_from_hash(hash); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def local_store; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def local_store=(_arg0); end

  # A callable (trace_hash, sdk_hash) that persists traces in-process —
  # the ActiveAgent dashboard wires this to its TelemetryTrace model.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:71
  def local_store?; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def logger; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def logger=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def open_timeout; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def open_timeout=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def redact_attributes; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def redact_attributes=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:117
  def resolved_environment; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:121
  def resolved_logger; end

  # Falls back to the Rails application name, then to a generic label, so
  # traces are attributable even when the app never sets one.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:113
  def resolved_service_name; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def resource_attributes; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def resource_attributes=(_arg0); end

  # Head-based sampling: decided once per trace, at report time.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:84
  def sample?; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def sample_rate; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def sample_rate=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def service_name; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def service_name=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:90
  def should_sample?; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def timeout; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:29
  def timeout=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:125
  def to_h; end

  private

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:143
  def rails_app_name; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:151
  def rails_env; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:155
  def rails_logger; end
end

# The hosted platform. Self-hosters override `endpoint`.
#
# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:20
ActiveAgents::Telemetry::Configuration::DEFAULT_ENDPOINT = T.let(T.unsafe(nil), String)

# Attribute keys scrubbed from spans before delivery. Name-based — a
# secret inside free text is not caught; see the wiki's privacy page.
#
# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:27
ActiveAgents::Telemetry::Configuration::DEFAULT_REDACT_ATTRIBUTES = T.let(T.unsafe(nil), Array)

# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:92
ActiveAgents::Telemetry::Configuration::FLOAT_SETTINGS = T.let(T.unsafe(nil), Array)

# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:93
ActiveAgents::Telemetry::Configuration::INTEGER_SETTINGS = T.let(T.unsafe(nil), Array)

# Path a mounted ActiveAgent::Dashboard::Engine serves traces on.
#
# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/configuration.rb:23
ActiveAgents::Telemetry::Configuration::LOCAL_ENDPOINT_PATH = T.let(T.unsafe(nil), String)

# Delivers traces to the configured endpoint.
#
# Telemetry is never worth breaking an app over, so every failure path here
# ends in a log line: a bad endpoint, a down collector, a serialization bug
# in an adapter, and a nil api_key all degrade to "no traces" rather than an
# exception in the caller's request cycle.
#
# Delivery is fire-and-forget on a thread by default. Pass `async: false`
# for tests, or for scripts short enough that the process may exit before a
# background thread flushes.
#
# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:19
class ActiveAgents::Telemetry::Reporter
  # @param sdk_name [String] overridden by adapters so ingest can tell
  #   which integration produced a trace.
  # @param sample [Boolean] pass false when the caller already applied
  #   head-based sampling at trace creation — sampling twice compounds
  #   the rate to rate².
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:29
  def initialize(configuration, sdk_name: T.unsafe(nil), sdk_version: T.unsafe(nil), sample: T.unsafe(nil)); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:22
  def configuration; end

  # @param traces [Trace, Hash, Array<Trace, Hash>] traces to deliver —
  #   Trace objects or already-serialized trace hashes
  # @return [void]
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:39
  def report(traces); end

  # Blocking delivery, for tests and for at-exit flushes.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:54
  def report_now(traces); end

  private

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:77
  def deep_stringify(value); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:121
  def deliver(body); end

  # Hands each trace to the configured local store instead of HTTP —
  # nothing leaves the process. Per-trace rescue: one bad row must not
  # drop its batch-mates.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:150
  def deliver_locally(body); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:159
  def log(message); end

  # Array() is wrong here: it would explode a raw trace hash into
  # key/value pairs. Traces arrive as Trace objects or serialized hashes,
  # singly or in arrays.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:67
  def normalize(traces); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:89
  def payload_for(traces); end

  # Scrubs span attributes whose key matches the configured redaction
  # list. Matching is by attribute key segment ("api_key", "http.api_key"),
  # not by value — a secret inside free text is not caught here.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:104
  def redact(trace_hash); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:85
  def sample_trace?; end

  # Trace#to_h is already string-keyed; raw hashes may arrive symbol-keyed
  # and both local stores and ingest read string keys.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:73
  def serialize(trace); end
end

# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/reporter.rb:20
ActiveAgents::Telemetry::Reporter::SDK_NAME = T.let(T.unsafe(nil), String)

# A single operation inside a trace, serialized to the `/v1/traces` wire
# format. Adapters build these rather than hand-rolling hashes, so a span
# from the RubyLLM adapter and a span from any future adapter are shaped
# identically on the wire.
#
# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:11
class ActiveAgents::Telemetry::Span
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:23
  def initialize(name, type:, trace_id: T.unsafe(nil), parent_span_id: T.unsafe(nil), span_id: T.unsafe(nil), attributes: T.unsafe(nil), start_time: T.unsafe(nil)); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:89
  def add_event(name, attributes = T.unsafe(nil)); end

  # Builds a child span sharing this span's trace. Instrumentation that
  # holds only a span — not the enclosing trace — nests through this;
  # Trace#to_h flattens the tree back out for the wire.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:51
  def add_span(name, type: T.unsafe(nil), **options); end

  # Adds another span's token counts to this one — how a turn-level llm
  # span accumulates the rounds it covers.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:83
  def add_tokens(other); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:20
  def attributes; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:20
  def children; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:121
  def duration_ms; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:21
  def end_time; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:21
  def end_time=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:20
  def events; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:111
  def finish(at: T.unsafe(nil)); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:117
  def finished?; end

  # Runs the block, recording its outcome and timing on the span.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:146
  def measure; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:20
  def name; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:21
  def parent_span_id; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:21
  def parent_span_id=(_arg0); end

  # Records an error without ever putting a backtrace or an untruncated
  # message on the wire — telemetry payloads leave the app's trust boundary.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:103
  def record_error(error, message_limit: T.unsafe(nil)); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:57
  def set_attribute(key, value); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:62
  def set_attributes(attrs); end

  # @param code [Symbol, String] :ok, :error, or :unset
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:95
  def set_status(code, message = T.unsafe(nil)); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:67
  def set_tokens(input: T.unsafe(nil), output: T.unsafe(nil), thinking: T.unsafe(nil)); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:20
  def span_id; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:21
  def start_time; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:21
  def start_time=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:21
  def status; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:21
  def status=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:20
  def status_message; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:127
  def to_h; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:77
  def tokens; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:39
  def trace_id; end

  # Stamping a trace_id propagates to children, so a subtree built before
  # its trace exists still lands in one piece.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:43
  def trace_id=(value); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:20
  def type; end

  private

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:167
  def iso8601(time); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:159
  def stringify(hash); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:163
  def truncate(string, limit); end
end

# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:15
ActiveAgents::Telemetry::Span::ERROR = T.let(T.unsafe(nil), String)

# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:14
ActiveAgents::Telemetry::Span::OK = T.let(T.unsafe(nil), String)

# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:12
ActiveAgents::Telemetry::Span::TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:16
ActiveAgents::Telemetry::Span::UNSET = T.let(T.unsafe(nil), String)

# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/span.rb:18
ActiveAgents::Telemetry::Span::ZERO_TOKENS = T.let(T.unsafe(nil), Hash)

# A collection of spans sharing a trace_id, plus the service metadata the
# ingest endpoint keys on. Adapters build one per unit of work — for chat
# adapters, one per conversation turn.
#
# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:10
class ActiveAgents::Telemetry::Trace
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:14
  def initialize(trace_id: T.unsafe(nil), service_name: T.unsafe(nil), environment: T.unsafe(nil), resource_attributes: T.unsafe(nil)); end

  # Adopts the span into this trace, stamping the trace_id so adapters
  # cannot emit a span that belongs to no trace.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:24
  def add_span(span); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:39
  def empty?; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:12
  def environment; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:12
  def environment=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:12
  def resource_attributes; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:12
  def resource_attributes=(_arg0); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:35
  def root; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:12
  def service_name; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:12
  def service_name=(_arg0); end

  # Builds and adopts a span in one step.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:31
  def span(name, type:, parent: T.unsafe(nil), **options); end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:11
  def spans; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:43
  def to_h; end

  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:11
  def trace_id; end

  private

  # Spans built through Span#add_span nest as children; the wire format is
  # flat, with parentage carried by parent_span_id.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:58
  def flatten(span); end

  # The trace's own end time, so out-of-order delivery still lands the
  # trace at the moment it actually finished.
  #
  # pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/trace.rb:64
  def timestamp; end
end

# pkg:gem/activeagents-telemetry#lib/activeagents/telemetry/version.rb:5
ActiveAgents::Telemetry::VERSION = T.let(T.unsafe(nil), String)
