// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";
import ClickOnAppearController from "./click_on_appear_controller";
import HelloController from "./hello_controller";
import MaintainScrollController from "./maintain_scroll_controller";
import ScrollToBottomController from "./scroll_to_bottom_controller";
import TooltipController from "./tooltip_controller";
// import LoremPicsumController from "./lorem_picsum_controller";

application.register("hello", HelloController);
application.register("tooltip", TooltipController);
application.register("scroll-to-bottom", ScrollToBottomController);
application.register("click-on-appear", ClickOnAppearController);
application.register("maintain-scroll", MaintainScrollController);
