# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WhatsappGroupAgent::SendMessageHistoryLinkTool`.
# Please instead update this file by running `bin/tapioca dsl WhatsappGroupAgent::SendMessageHistoryLinkTool`.


module WhatsappGroupAgent::SendMessageHistoryLinkTool
  mixes_in_class_methods ::WhatsappMessaging::ClassMethods
end
