# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ForwardWebhookToDevServerJob`.
# Please instead update this file by running `bin/tapioca dsl ForwardWebhookToDevServerJob`.


class ForwardWebhookToDevServerJob
  class << self
    sig do
      params(
        body: ::String,
        webhook_signature: ::String,
        block: T.nilable(T.proc.params(job: ForwardWebhookToDevServerJob).void)
      ).returns(T.any(ForwardWebhookToDevServerJob, FalseClass))
    end
    def perform_later(body:, webhook_signature:, &block); end

    sig { params(body: ::String, webhook_signature: ::String).void }
    def perform_now(body:, webhook_signature:); end
  end
end
